# Generated by Django 4.0 on 2023-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_note_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
