# Generated by Django 4.0 on 2023-12-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_voice_note_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voice_note_blob',
        ),
        migrations.AddField(
            model_name='chat',
            name='voice_note_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
