# Generated by Django 4.0 on 2023-12-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_chat_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='voice_note_blob',
            new_name='voice_note_data',
        ),
    ]
