# Generated by Django 4.0 on 2024-01-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chat_voice_note_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='parent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
