# Generated by Django 4.0 on 2024-01-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chat_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.chat'),
        ),
    ]
