# Generated by Django 4.0 on 2024-01-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_chat_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
