# Generated by Django 4.0 on 2024-01-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_chat_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='media/chat_files/'),
        ),
    ]
