# Generated by Django 4.0 on 2024-01-03 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_chat_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
